### ISSUE TITLE
Why not only check the versions file?

### ISSUE THREAD

**Issue by merlinstardust** [clayne11/eslint-import-resolver-meteor#12]
Looking at the code, it seems you check the packages file if the import has a `:` in it and you check versions otherwise

Why not just check the versions file?

This would simplify the code. It would also mean that implied packages do not have to be added.

For instance, `aldeed:collection2` implies `aldeed:simple-schema` so I can import it. But this plugin expects me to have added `aldeed:simple-schema` at the top level.

**Comment by clayne11** [comment]
We had a discussion about that on https://github.com/clayne11/eslint-import-resolver-meteor/issues/1.

I also explained it a bit differently [here](https://github.com/clayne11/eslint-import-resolver-meteor/issues/4#issuecomment-219258034).

I'm open to discussion but I like explicit over implicit 99% of the time. It makes code much simpler to reason about by using explicit vs implicit dependencies and adding packages directly to your project isn't a huge burden.

**Comment by merlinstardust** [comment]
Yeah I can understand that reasoning. One other option could be to have it be a setting whether you care about implicit vs explicit packages.

Since Meteor is moving over to npm in the future, it might not even matter.

I'm going to explicitly add the packages because I agree with you that it does make more sense. So I'm closing this. Thanks for your thoughts
