### ISSUE TITLE
imports not getting resolved as expected

### ISSUE THREAD

**Issue by mhlmhl** [clayne11/eslint-import-resolver-meteor#19]
I had to reinstall my system, and am now having problems with import statements when I run eslint via "meteor npm run lint" or "npm run lint" and in sublime text.  This is on Windows 8.1 64-bit.

>    13:1   error  'meteor' should be listed in the project's dependencies. Run 'npm i -S meteor' to add it  import/no-extraneous-dependencies
>    13:29  error  Missing file extension for "meteor/reactive-var"                                          import/extensions
>    15:1   error  Do not import modules using an absolute path                                              import/no-absolute-path
>    15:21  error  Unexpected use of file extension "js" for "/imports/api/vocabulary/Message.js"            import/extensions

I think eslint-import-resolver-meteor is not working as expected, nor as it did work before my reinstallation.

I installed node and npm on their own in order to get them in my path so that SublimeLinter could find them.  I installed the same eslint plugins that I use both globally ("npm install --save-dev -g ..." ) and  locally ("meteor npm install ...") in case that makes a difference.

Here is my package.json file:

> {
>   "name": "QRBuilder_Meteor_1.4",
>   "private": "true",
>   "version": "0.0.0",
>   "description": "Quarule builder",
>   "main": "index.js",
>   "dependencies": {
>     "babel-runtime": "^6.18.0",
>     "bootstrap": "^3.3.6",
>     "core-js": "^2.4.1",
>     "css": "^2.2.1",
>     "deep-equal": "^1.0.1",
>     "double-ended-queue": "^2.1.0-0",
>     "encoding": "^0.1.12",
>     "fbjs": "^0.8.5",
>     "history": "^4.4.0",
>     "hoist-non-react-statics": "^1.2.0",
>     "iconv-lite": "^0.4.13",
>     "immutable": "^3.8.1",
>     "invariant": "^2.2.1",
>     "is-stream": "^1.1.0",
>     "isomorphic-fetch": "^2.2.1",
>     "js-tokens": "^2.0.0",
>     "lib": "^1.0.1",
>     "loose-envify": "^1.3.0",
>     "object-assign": "^4.1.0",
>     "promise": "^7.1.1",
>     "query-string": "^4.2.3",
>     "react": "^15.3.2",
>     "react-addons-create-fragment": "^15.3.2",
>     "react-addons-css-transition-group": "^15.3.2",
>     "react-addons-linked-state-mixin": "^15.1.0",
>     "react-addons-perf": "^15.3.2",
>     "react-addons-pure-render-mixin": "^15.3.2",
>     "react-addons-test-utils": "^15.3.2",
>     "react-addons-transition-group": "^15.3.2",
>     "react-addons-update": "^15.3.2",
>     "react-dom": "^15.3.2",
>     "react-router": "^2.8.1",
>     "strict-uri-encode": "^2.0.0",
>     "ua-parser-js": "^0.7.11",
>     "warning": "^3.0.0",
>     "whatwg-fetch": "^1.0.0"
>   },
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1",
>     "lint": "eslint .",
>     "pretest": "npm run lint --silent"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/Quarule/QRBuilder_Application.git"
>   },
>   "author": "",
>   "license": "Quarule confidential, all rights reserved, copyright",
>   "bugs": {
>     "url": "https://github.com/Quarule/QRBuilder_Application/issues"
>   },
>   "homepage": "https://github.com/Quarule/QRBuilder_Application",
>   "eslintConfig": {
>     "plugins": [
>       "meteor"
>     ],
>     "extends": [
>       "airbnb",
>       "plugin:meteor/recommended"
>     ],
>     "rules": {}
>   },
>   "devDependencies": {
>     "babel-eslint": "^7.1.0",
>     "eslint": "^3.9.1",
>     "eslint-config-airbnb": "^13.0.0",
>     "eslint-import-resolver-meteor": "^0.3.3",
>     "eslint-plugin-import": "^2.2.0",
>     "eslint-plugin-jsx-a11y": "^2.2.3",
>     "eslint-plugin-meteor": "^4.0.1",
>     "eslint-plugin-react": "^6.6.0"
>   }
> }

And my .eslintrc file:

> {
>   "plugins": [
>     "meteor",
>     "react"
>   ],
>   "extends": [
>     "airbnb",
>     "eslint:recommended",
>     "plugin:meteor/recommended"
>   ],
>   "installedESLint": true,
>   "parserOptions": {
>     "ecmaVersion": 6,
>     "sourceType": "module",
>     "ecmaFeatures": {
>         "jsx": true,
>         "impliedstrict" : true,
>         "experimentalObjectRestSpread" : true
>     }
>   },
>   "rules": {
>         "semi": 2
>     },
>   "env": {
>     "es6": true,
>     "browser": true,
>     "node": true,
>     "meteor": true
>   },
>   "settings": {
>     "react": {
>       "pragma": "React",  // Pragma to use, default to "React"
>       "version": "15.0", // React version, default to the latest React stable release
>     },
>     "import/resolver": { "meteor": {"extensions": [".js", ".jsx"]} },
>   },    
>   "scripts": {
>     "lint": "eslint .",
>     "pretest": "npm run lint --silent"
>   },
>   "eslintConfig": {
>     "plugins": [
>       "meteor"
>     ]
>   },
>   "indent": [2, 2]
> }
> 
>

**Comment by HenriBeck** [comment]
This is not a problem with the resolver.

The resolver only makes no-unresolved errors.

You can fix no-extraneous-dependencies and import/extensions with adding the meteor packages to import/core-modules

For example:

```js
settings: {
    'import/core-modules': fs.readFileSync('./.meteor/packages', 'utf-8')
      .split('\n')
      .filter(name => name.charAt(0) !=='#')
      .filter(name => name.length > 0)
      .map(name => name.indexOf('@') > -1 ? name.split('@')[0] : name)
      .map(name => 'meteor/' + name)
      .concat(['meteor/meteor'])
  },
```
This will get all off your packages and make them core-modules

Note: This will only work when your eslintrc is a js file.

**Comment by HenriBeck** [comment]
If you want to use absolute paths you will want to turn of import/no-absolute-path.

There is no other way around this.

And about the extensions:

You can fix it by adding this to your rules object
```js
'import/extensions': ['error', 'always', {
      js: 'always',
      jsx: 'always',
    }],
```

**Comment by mhlmhl** [comment]
I did fix this problem.  I believe it was because I had my project installed on a Google Drive.  I was anxious to get started on my work, so I downloaded it from Drive before Drive had finished synching.  So then Drive saw synchronization conflicts and created duplicate files named "... (1)..."  The problem went away when I deleted the duplicate files.
