### ISSUE TITLE
adding to .eslintrc

### ISSUE THREAD

**Issue by binarytracer** [clayne11/eslint-import-resolver-meteor#3]
do you think we can add this directly to existing .eslintrc? if we can, how?

**Comment by clayne11** [comment]
Do you mean one that doesn't use [`YAML`](http://yaml.org/)? You can definitely do that! `YAML` is simply a different markup language similar to `JSON` but more readable.

In `JSON` your  config would look something like this:

``` json
{
  "plugins": [
    "import"
  ],
  "settings": {
    "import/resolver": {
      "meteor": {
        "extensions": [
          ".js",
          ".jsx"
        ],
        "moduleDirectory": [
          "node_modules"
        ]
      }
    }
  }
}
```

Hopefully that helps.

**Comment by clayne11** [comment]
Closing. This question has been answered.

**Comment by merlinstardust** [comment]
Can this be added to the readme for ease of finding it in the future?
