### ISSUE TITLE
Import Parsing - comments in .meteor/packages

### ISSUE THREAD

**Issue by ExcelNet-Public** [clayne11/eslint-import-resolver-meteor#4]
We use a hand written packages file in our Meteor applications which include comments about the packages being included.  This confuses your package and causes the importer to mark as error.  An example line might be:

alanning:roles                                      # Authorization 

My suggestion is to trim all trailing white space and/or comments from each line when testing as this will simply make it more robust.

Second, it does not seem to handle relative paths:

import { MyClass} from '../myClass.js';

This will be flagged as well.  Thanks for creating this package!

**Comment by clayne11** [comment]
Thanks for reporting this. I will update the package to support comments. I didn't realize that was a possibility.

Relative paths are working fine for me though - are you able to post a reproduction?

**Comment by ExcelNet-Public** [comment]
```
/    Project root
imports/
  api/
    news/
      news.js
      server/
        publications.js
```

publications.js:

import { News} from '../news.js';

That line will get marked in error for me.  If I change it to:

import { News} from '/imports/api/news/news.js';  

That will not generate an error in the linting. Don't know if this has to do with it being nested a couple of levels, but possibly.  Thanks for the quick response!

**Comment by clayne11** [comment]
Are you able to provide a cloneable repo on Github so that I can download it, reproduce it myself, and fix it? I'm unable to reproduce this in my project.

If you post a reproduction repo I'd be happy to fix it.

Thanks!

**Comment by ExcelNet-Public** [comment]
Hmm, I cannot reproduce either any more.  I changed the line back in my original project to the relative path and it is not giving an error any longer.  Sorry for the confusion.

**Comment by clayne11** [comment]
No problem.

I'll make the fix for comments when I have a minute, probably this weekend.

**Comment by ExcelNet-Public** [comment]
Thanks, appreciate it!

**Comment by clayne11** [comment]
I fixed this in `v0.2.1`. Please try it and report back.

**Comment by ExcelNet-Public** [comment]
I pulled in 0.2.2 as that was latest.  It is not working for me, but I am unclear as to why.  The regex appears to be correct and I tested it against the file and it should match.  

However, after digging into the code I am not sure why you are looking at packages at all.  All of the non-meteor packages get put into versions as well so just checking that should be sufficient.  When I change the code to ignore packages and just use versions:

   `var packageCheckFile = getVersionFile(meteorRoot);`

Then it all lints correctly.

You can also simplify the regex a bit to:

```
var found = new RegExp('^' + package + '(?:@.*|\s+#.*)?$', 'm').test(packageCheckFile);
```

Since you are not interested in what is captured.

**Comment by clayne11** [comment]
Can you post a reproduction repo for me to look at?

I'm using `.meteor/packages` because versions can contain a lot of packages that you didn't didn't add to the project yourself. All of the dependencies of your dependencies end up in there, so you can easily end up with false positives for packages that are in your `.meteor/versions` but that you didn't intentionally add or that you didn't even know were there.

This isn't as much of an issue with the internal Meteor packages because a lot of them are in `versions` by default due to packages like `meteor-base` and for newer users it doesn't necessarily make sense to have them include all of the internal packages directly to their project.

If anything, I would argue that if anything we should only check `packages` and not `versions` at all, not the other way around.

**Comment by ExcelNet-Public** [comment]
Yes, I agree with the argument for only packages being a better solution for most accurate linting.  I have a repo you can clone at:

https://bitbucket.org/excelnetpublic/importtest.git

Thanks!

**Comment by clayne11** [comment]
I'm having trouble figuring out why this is happening.

If I remove the `$` at the end of the RegEx the match works. I've tested the current RegEx on [https://regex101.com](https://regex101.com) and it's matching with your package file so I'm not sure what's going on.

**Comment by clayne11** [comment]
If I replace the `\s` with a literal ` ` it works. I'm really not sure why that is, but I'm going to put in a few different literal whitespace characters and republish.

**Comment by clayne11** [comment]
Published under `v0.2.3`

**Comment by ExcelNet-Public** [comment]
Yes, this version works for me.  Very odd you had to replace the \s with the group of them, technically should be the same thing.  Thanks!

**Comment by clayne11** [comment]
It is very odd. Glad we could get it fixed though. Thanks for the help!
