### ISSUE TITLE
Forbid import server/client code from common

### ISSUE THREAD

**Issue by dikmax** [clayne11/eslint-import-resolver-meteor#6]
For example consider file `imports/common/file.js`:

``` js
import '../client/file.js';
```

This will lead to a server, that unable to import this file. The only case when it doesn't shows error is when `common/file.js` isn't used on the server at all. In that case, it's better to move it somewhere under `client`.

**Comment by clayne11** [comment]
Good call. I didn't realize that the `client` and `server` folders were actually enforced by Meteor under the `imports` folder. I will fix this sometime this week.

**Comment by clayne11** [comment]
Published in `v0.2.4`

**Comment by dikmax** [comment]
Thank you!
