### ISSUE TITLE
Unable to resolve path for relative .js or .jsx files

### ISSUE THREAD

**Issue by mhlmhl** [clayne11/eslint-import-resolver-meteor#7]
I am having trouble importing both .js and .jsx files when using relative paths.  The imports work fine if I specify an absolute path, but fail with import/no-unresolved when I use relative paths.

For example, I have two files in the same folder:
/imports/api/vocabulary/Message.js
/imports/api/vocabulary/BaseModel.js

in BaseModel.js, this statement works fine: 
import { Message } from '/imports/api/vocabulary/Message.js';

... and both of these get "Error: Unable to resolve path to module './Message.js'. (import/no-unresolved)"
import { Message } from './Message.js';
import { Message } from 'Message.js';

Furthermore, these worked last week (using the "./..." format) when I last worked on them.  But when I happened to edit them yesterday evening, they showed this lint error.  What I changed between last week and yesterday is that I updated my eslint plugins to the latest.

My .eslintrc:

{
"plugins": [
"meteor",
"react"
],
"extends": [
"airbnb",
"plugin:meteor/recommended"
],
"parserOptions": {
"ecmaVersion": 6,
"sourceType": "module",
"ecmaFeatures": {
"jsx": true,
"impliedstrict" : true
}
},
"rules": {
"semi": 2
},
"env": {
"es6": true,
"browser": true,
"node": true,
"meteor": true
},
"settings": {
"react": {
"pragma": "React", // Pragma to use, default to "React"
"version": "15.0" // React version, default to the latest React stable release
},
"import/resolver": { "meteor": {"extensions": [".js", ".jsx"]} },
},

"scripts": {
"lint": "eslint .",
"pretest": "npm run lint --silent"
},
"eslintConfig": {
"plugins": [
"meteor"
]
},
"indent": [2, 2]
}

**Comment by clayne11** [comment]
Can you post a reproduction repo for me? I can't reproduce the problem.

**Comment by benmosher** [comment]
FWIW, I've seen this happen inside Sublime for reasons that are not all well understood. Would be good to know how you're executing `eslint`, too. (i.e. does it work from the command line?)

**Comment by clayne11** [comment]
No response from OP so I'm going to close this. Feel free to re-open if you're still having issues.

**Comment by PolGuixe** [comment]
@clayne11 I am having these problem as well, which is fixed by adding the extension of the file. 
Does the resolved takes into consideration different file extensions?

**Comment by clayne11** [comment]
You can update which file extensions automatically resolve in your `eslintrc`:

```javascript
module.exports = {
  'settings': {
    'import/resolver': {
      'meteor': {
        'extensions': [
          '.js',
          '.jsx'
        ],
        'moduleDirectory': [
          'node_modules',
        ]
      }
    },
    'import/ignore': [
      'node_modules',
      '\.scss$',
    ],
  },
}
```
