### ISSUE TITLE
Allow override of Meteor project directory

### ISSUE THREAD

**Issue by damonmaria** [clayne11/eslint-import-resolver-meteor#9]
I have a more complicated Meteor setup where all the code is in one directory, but then used in 2 Meteor projects using symlinks. I use ESLint to ensure I don't import from the wrong places (e.g. server code imports client only code). At the moment I have a symlink at the top of this combined code to one of the `.meteor` directories and so the package list in this Meteor is what your plugin is checking against. I would like to be able in a per-directory `.eslintrc` specify which Meteor project directory this resolver should be checking against. Would that be possible? 

P.S. Love this plugin. I was contemplating the headache of writing exactly the same when I came across it.

**Comment by clayne11** [comment]
I'm sure it's possible. Are you interested in doing a PR for it? I'm pretty busy at the moment and this isn't a feature that I personally need.

If you don't want to do it I'll get to it eventually but it will probably be a couple months.

**Comment by damonmaria** [comment]
Sure. I'll have a go.

**Comment by chmanie** [comment]
How about defining a `meteorDir` like this:

```yaml
settings:
  import/resolver:
    meteor:
      # directory in which the .meteor folder lies
      meteorDir: app
```

I pretty much have this ready. I could submit a PR.
